/*
Credit Card transaction Analysis | Report Creation | Customer Segmentation

Skills used: Joins, CTE's, Windows Functions, Aggregate Functions, CASE, Converting Data Types

--==> This means insights/inferences
*/

--Let's explore the dataset   

--Get the range of dates for the transaction data

Select min(transaction_date) , max(transaction_date) 
from transactions

--==> Data is from 4th october 2013 to 26th may 2015 

-- What are the types of cards

Select distinct(card_type) 
from transactions

--==> Silver,Signature,Gold,Platinum

-- What are the types of expenditure

Select distinct(exp_type) 
from transactions

--==> Entertainment , Food, Bills, Fuel, Travel, Grocery

-- What is the number of cities using credit card

Select COUNT(distinct(city)) from transactions

--==> The number of cities using credit card is 986


--1.Total Amount spent on different categories in year 2014

Select DATEPART(Year,transaction_date) as Year, exp_type, sum(amount) as Total_amount
from transactions
where DATEPART(Year,transaction_date) = 2014
group by exp_type,DATEPART(Year,transaction_date)
order by Total_amount Desc

--==> FINDINGS- EXP_TYPE-BILLS IS THE CATEGORY ON WHICH MAXIMUM AMOUNT HAS BEEN SPENT IN YEAR 2014


--2. What is the best revenue generating card

Select card_type, sum(amount) as Total_amount
from transactions
group by card_type
order by Total_amount Desc

--==> FINDINGS- SILVER


--3.What are the Bottom 5 Revenue generating cities

Select Top 5 city,Sum(amount) as Total_Revenue_Per_City
from transactions
group by city
order by Total_Revenue_Per_City asc;


--==> FINDINGS -Fazilka,Mahbubnagar,Bahraich,Tirur,Changanassery

--4.What is the total revenue generated by each gender in different year

Select DatePart(Year,transaction_date) as Year,gender,Sum(amount) as Total_Revenue_By_Gender
from transactions
group by gender,DatePart(Year,transaction_date)
order by  Total_Revenue_By_Gender desc;

--==> FINDINGS- Every year Female generated more revenue than male


--5.What are the Top 5 cities with highest spends and their percentage contribution of total credit card spends

with cte1 as (
select city,sum(amount) as total_spend
from transactions
group by city)
,total_spent as 
(select sum(amount) as total_amount from transactions)
select top 5 cte1.*, 
round(total_spend*1.0/total_amount * 100,2) as percentage_contribution from 
cte1 inner join total_spent on 1=1
order by total_spend desc;

--==> FINDINGS - Greater Mumbai-14.15% , Bengaluru- 14.05 % ,  Ahmedabad - 13.93%  ,Delhi- 13.67% ,  Kolkata-2.83%

 
 --6. For each card type what is the highest spend month and amount spent in that month 


With CTE as 
(
Select card_type,DATEPART(year,transaction_date) as Year,DATEPART(MONTH,transaction_date) as month,SUM(amount) as amount_spent
from transactions
group by card_type,DATEPART(year,transaction_date),DATEPART(month,transaction_date)
),
Highest_spent_month as
( 
   Select * ,
   RANK() over(partition by card_type order by amount_spent desc) as rnk
   from CTE)
Select * from Highest_spent_month 
where rnk = 1;

--==> FINDINGS- For Silver highest spent month is march , For Signature highest spent month is December,For Platinum highest spent month is  
              --August and For Gold highest spent month is  January


-- 7. What is the transaction details for each card type when it reaches a cumulative of 1000000 total spends	

With CTE as 
(
Select *,SUM(amount)over(Partition by card_type order by transaction_date,id) as amount_spent
from transactions
),
rank1 as
(
 Select * ,
 RANK()over(partition by card_type order by amount_spent) as rn
 from CTE 
 where amount_spent>=1000000
 )
select * from rank1
where rn = 1

--==> FINDINGS - Delhi - Gold,   Ahmedabad - Platinum , Delhi - Signature , Bengaluru- Silver

-- 8.Which city had lowest percentage spend for gold card type

With CTE as
(
Select city,card_type,SUM(amount) as amnt_spent,
SUM(case when card_type ='Gold' then amount end) as gold_amount
from transactions
group by city,card_type
)
Select Top 1 city,SUM(gold_amount)*1.0/SUM(amnt_spent) as gold_ratio
from CTE
group by city
having SUM(gold_amount) is not null
order by gold_ratio

--==> FINDINGS - Dhamtari, India


--9. For each city find highest expense type and  lowest expense type 

With CTE as
(
Select city,exp_type,SUM(amount) as amount_spent
from  transactions
group by city,exp_type
),highest_lowest_type as
(
 Select * ,
RANK() over(Partition by city order by amount_spent desc)as hrn,
RANK() over(Partition by city order by amount_spent )as lrn
from CTE 
)
Select city,
MAX(case when hrn=1 then exp_type end) as highest_expense_type,
MAX(case when lrn=1 then exp_type end) as lowest_expense_type
from highest_lowest_type
group by city;

--==> FINDINGS- example for  Achalpur, India  ,Grocery is the highest expense type and entertainment is the lowest expense type 


-- 10.What is the percentage contribution of spends by females for each expense type as compare to males

With CTE as
(
Select exp_type, SUM(amount) as amount_spent,
SUM(Case when gender = 'F' then amount else 0 end) as Female_amnt_spent
from transactions
group by exp_type
)
Select exp_type,
(Female_amnt_spent * 1.0/amount_spent) as percentage_contribution_by_females
from CTE;

--==> FINDINGS - Entertainment -49%   ,   Food-54%   ,  Bills-63%   ,  Fuel-49%   ,  Travel-51%,  Grocery-50%

--11. Which card and expense type combination saw highest month over month growth % in Jan-2014

With CTE as
(
Select card_type,exp_type,DATEPART(year,transaction_date) as yt,DATEPART(month,transaction_date) as mt,
SUM(amount) as amnt_spent
from transactions
group by card_type,exp_type,DATEPART(year,transaction_date),DATEPART(month,transaction_date) 
),Previous_month_growth as
( 
Select * ,
LAG(amnt_spent,1) over ( partition by card_type,exp_type order by yt,mt) as Prev_month_amnt_spent
from CTE)
Select Top 1 *, Round((amnt_spent-Prev_month_amnt_spent)*1.0/Prev_month_amnt_spent * 100,2) as MOM_growth
from Previous_month_growth
where yt = '2014' and mt='1'
order by MOM_growth desc;

--==> FINDINGS - Gold and Travel expense type shows the highest MOM growth % in January 2014


--12. Which city has the highest total spend to total no of transcations ratio during weekends 

Select top 1 city,sum(amount)*1.0/count(*) as Ratio
from transactions
where Datename(weekday,transaction_date) IN ( 'Saturday','Sunday')
group by city
order by Ratio desc;

--==> FINDINGS- Sonepur, India has the highest spend-to-transaction ratio during weekends

--13. Which city took least number of days to reach its 500th transaction after the first transaction in that city

With CTE as
(
Select * ,
row_number() over (partition by city order by transaction_date,id) as rn
from transactions
)
Select top 1 city, datediff(day, min(transaction_date),max(transaction_date)) as diff
from CTE
where rn=1 or rn=500
group by city
having count(*)=2
order by diff

--==> FINDINGS- Bengluru took 81 days to reach 500th transaction

--14.Generate Yearly Revenue Report and categorize card types into tiers based on their revenue contribution.

Select card_type, Sum(amount) as Total_Revenue_Per_Card_Type,
Case 
    when Sum(amount) > 1010000000 Then 'Tier 1'
	when Sum(amount) < 1010000000 Then 'Tier 2'
	end as card_category,
SUM(Case when transaction_date Between '2013-01-01' AND '2014-01-01' then amount else 0 end) as Revenue_2013,
SUM(Case when transaction_date Between '2014-01-01' AND '2015-01-01' then amount else 0 end) as Revenue_2014,
SUM(Case when transaction_date Between '2015-01-01' AND '2015-12-31' then amount else 0 end) as Revenue_2015
from transactions
group by card_type
order by Total_Revenue_Per_Card_Type desc

--FINDINGS - Silver and Signature are the best performing card types each year